In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.0


In [12]:
array_1d = np.array([1, 2, 3, 4,5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [16]:
import numpy as np
# 1D array
array_1d = np.arange(1, 6)
# 2D array
array_2d = np.arange(1, 7).reshape(2, 3)

# Attributes of the 1D array
print("1D Array:")
print("Array:", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)
# Attributes of the 2D array
print("\n2D Array:")
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)

# Array with specified data type
array_float = np.arange(1, 4, dtype=float)
print("\nArray with float data type:")
print("Array:", array_float)
print("Data type:", array_float.dtype)

1D Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64

2D Array:
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64

Array with float data type:
Array: [1. 2. 3.]
Data type: float64




    A one dimensional array with the temperatures from this week.
    A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
    A 3D array with valid pixel values for a picture with 9 pixels.



In [19]:
array_temperature = np.array([25, 30, 32, 34, 38, 29])
# Attributes of the 1D array
print("1D Array:")
print("Array:", array_temperature)
print("Shape:", array_temperature.shape)
print("Size:", array_temperature.size)
print("Data type:", array_temperature.dtype)

1D Array:
Array: [25 30 32 34 38 29]
Shape: (6,)
Size: 6
Data type: int64


In [26]:
# 2D array
array_2d = np.arange(1, 11).reshape(2, 5)
# Attributes of the 2D array
print("\n2D Array:")
print("Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)


2D Array:
Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Size: 10
Data type: int64


In [28]:
array_3d = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
print("\n3D Array:")
print("Array:\n", array_3d)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Data type:", array_3d.dtype)


3D Array:
Array:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
Shape: (3, 3)
Size: 9
Data type: int64


In [29]:

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]




1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.

2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.

3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.

4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

Expected Output:

    The 5th element of the first array.
    A slice of the array showing elements from the 3rd to the 8th position.
    Elements greater than 30 from the random array.
    Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.



In [ ]:
array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
print("\n1D Array:")
print("Array:\n", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)
array_1d[5:6]
array_1d[2:9]


3D Array:
Array:
 [0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
Size: 10
Data type: int64


array([2, 3, 4, 5, 6, 7, 8])

In [36]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[46 41 45]


In [ ]:
import numpy as np
# Create an array with 10 elements
array_10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Access the 5th element (index 4)
fifth_element = array_10[4]
print("5th element:", fifth_element)

# Extract elements from the 3rd to the 8th position (indices 2 to 7)
slice_array = array_10[2:8]
print("Slice from 3rd to 8th elements:", slice_array)

# Create an array of 6 random integers between 10 and 50
random_array = np.random.randint(10, 50, 6)
# Boolean indexing to find elements greater than 30
greater_than_30 = random_array[random_array > 30]
print("Random array elements greater than 30:", greater_than_30)

# Use fancy indexing to access 2nd, 4th, and 6th elements
fancy_elements = random_array[[1, 3, 5]]
print("Elements at 2nd, 4th, and 6th positions:", fancy_elements)

In [41]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new



array([2, 7, 5, 6, 1, 4, 3])

In [40]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[3, 4],
       [1, 2],
       [5, 6]])

In [43]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]


In [49]:
arr[1:4] = [20, 30, 40]
print(arr)  # Output: [1, 20, 30, 40, 5]

[ 1 20 30 40  5]




After learning about array indexing and slicing, it's important to practice these concepts. Here are some exercises to help solidify your understanding:

1. Modifying Specific Elements:

Create an array with values from 1 to 10. Change the value of the fifth element to 50.

2. Slicing and Modifying a Range:

Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.

3. Conditional Modification with Boolean Indexing:

Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.

4. Advanced Indexing Modification:

Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

5. Understanding Slicing Impact:

Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.


In [50]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("\n1D Array:")
print("Array:\n", array_1d)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)
array[4] = 50
print(array)


1D Array:
Array:
 [ 1  2  3  4 50  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int64
[ 1  2  3  4 50  6  7  8  9 10]


In [51]:
# Modify elements from index 3 to 7
array[3:8] = -array[3:8]
print("Array after negating elements 3 to 7:", array)

Array after negating elements 3 to 7: [  1   2   3  -4 -50  -6  -7  -8   9  10]


In [52]:
# Random array with values between 1 and 100
random_array = np.random.randint(1, 101, 20)
# Set elements greater than 50 to -1
random_array[random_array > 50] = -1
print("Array after setting values > 50 to -1:", random_array)

Array after setting values > 50 to -1: [43 14 47 -1  2  3 46 18 -1 16 23  3 -1 -1 -1 -1 -1 30 -1 -1]


Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

In [ ]:
# Correction 1 : La syntaxe pour créer un array 2D nécessite des parenthèses supplémentaires
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], [])  # Notez les doubles crochets

print("Array:\n", a)
print("Shape:", a.shape)  # Affiche les dimensions (2,5)
print("Size:", a.size)    # Nombre total d'éléments (10)
print("Data type:", a.dtype)  # Type des éléments (int64 par défaut)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Size: 10
Data type: int64


In [56]:
random_int_array = np.random.randint(0, 101, size=(5, 5))
print("Array d'entiers aléatoires :\n", random_int_array)

Array d'entiers aléatoires :
 [[ 9 29 56 76 67]
 [39 10 92 56 14]
 [39 36 89 89 48]
 [88 81 98 12 32]
 [50 55 74 35 94]]


In [57]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [58]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [60]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [62]:
import numpy as np

# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [[1]
 [2]
 [3]]
2D Array: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [63]:

# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))


Sum: 21
Mean: 3.5
Min: 1 Max: 6




1. Arithmetic Operations: Create two 1D arrays of 3 elements each and perform element-wise addition, subtraction, multiplication, and division.

2. Aggregation Functions: For the arrays created above, find the sum, mean, minimum, and maximum of each array.

3. Broadcasting with Scalar: Multiply one of the arrays by a scalar (e.g., 5) and observe the result.


In [64]:
# Creating two arrays
a = np.array([4, 5, 6])
b = np.array([1, 2, 3])
# Adding the two arrays
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)


1D Array: [4 5 6]
2D Array: [1 2 3]
Broadcasted Addition: [5 7 9]


In [65]:
# Sub the two arrays
result = a - b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [4 5 6]
2D Array: [1 2 3]
Broadcasted Addition: [3 3 3]


In [66]:
# Multiply the two arrays
result = a * b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [4 5 6]
2D Array: [1 2 3]
Broadcasted Addition: [ 4 10 18]


In [67]:
# Divide the two arrays
result = a / b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [4 5 6]
2D Array: [1 2 3]
Broadcasted Addition: [4.  2.5 2. ]


In [68]:

# Sum of all elements
print("Sum:", np.sum(a))

# Mean value
print("Mean:", np.mean(a))

# Minimum and Maximum
print("Min:", np.min(a), "Max:", np.max(a))

Sum: 15
Mean: 5.0
Min: 4 Max: 6


In [69]:
# Create a 2D array (shape 5x5)
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

# Multiply by scalar 5 (broadcasting)
result = arr * 5

print("Original Array:\n", arr)
print("\nAfter multiplying by 5:\n", result)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

After multiplying by 5:
 [[  5  10  15  20  25]
 [ 30  35  40  45  50]
 [ 55  60  65  70  75]
 [ 80  85  90  95 100]
 [105 110 115 120 125]]


In [70]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:

# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)


Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]




1. Reshape Array: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.

2. Transpose Matrix: Transpose the 2x6 matrix you created in the previous step.

3. Combine Reshaping and Transposing: Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.


In [76]:
a = np.arange(0, 12)
print(a)

# Reshaping to a 4x3 matrix
reshaped_array = a.reshape(4, 3)
print("Reshaped to 3x3:\n", reshaped_array)

# Reshaping to a 2x6 matrix
reshaped_array = a.reshape(2, 6)
print("Reshaped to 3x3:\n", reshaped_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Reshaped to 3x3:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [77]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [82]:
# Random integers (0-9)
array = np.random.randint(0, 10, size=(3, 4))

print("\nRandom integer matrix:\n", array)

# Transposing the reshaped array
transposed_array = array.T
print("Transposed array:\n", transposed_array)

# Reshaping to a 1x12 matrix
reshaped_array = transposed_array.reshape(1, 12)
print("Reshaped to 1x12\n", reshaped_array)




Random integer matrix:
 [[6 1 9 1]
 [8 6 4 3]
 [4 0 7 4]]
Transposed array:
 [[6 8 4]
 [1 6 0]
 [9 4 7]
 [1 3 4]]
Reshaped to 1x12
 [[6 8 4 1 6 0 9 4 7 1 3 4]]


In [85]:
# Create a 3x4 matrix
matrix_3x4 = np.arange(12).reshape(3, 4)
print("\n3x4 Matrix:\n", matrix_3x4)
# Transpose the 3x4 matrix
transposed_3x4 = matrix_3x4.T
print("\nTransposed 3x4 Matrix:\n", transposed_3x4)
# Reshape the transposed matrix to a 1D array
reshaped_1d = transposed_3x4.reshape(-1)
print("\nReshaped 1D Array from Transposed Matrix:\n", reshaped_1d)


3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed 3x4 Matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Reshaped 1D Array from Transposed Matrix:
 [ 0  4  8  1  5  9  2  6 10  3  7 11]
