In [ ]:
Exercise 1: Array Creation and Manipulation
python

import numpy as np

arr = np.arange(10)
print(arr)
# Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2: Type Conversion and Array Operations
python

import numpy as np

arr = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print(arr)
# Output: array([3, 2, 0, 1, 2])

Exercise 3: Working with Multi-Dimensional Arrays
python

import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print(arr)
# Output:
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

Exercise 4: Creating Multi-Dimensional Array with Random Numbers
python

import numpy as np

np.random.seed(0)  # For reproducibility
arr = np.random.rand(4, 5)
print(arr)
# Output will be random numbers in shape (4, 5)

Exercise 5: Indexing Arrays
python

import numpy as np

arr = np.array([[21,22,23,22,22],
                [20, 21, 22, 23, 24],
                [21,22,23,22,22]])
second_row = arr[1]
print(second_row)
# Output: array([20, 21, 22, 23, 24])

Exercise 6: Reversing elements
python

import numpy as np

arr = np.arange(10)
reversed_arr = arr[::-1]
print(reversed_arr)
# Output: array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 7: Identity Matrix
python

import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)
# Output:
# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])

Exercise 8: Simple Aggregate Funcs
python

import numpy as np

arr = np.arange(10)
total = np.sum(arr)
average = np.mean(arr)
print(f"Sum: {total}, Average: {average}")
# Output: Sum: 45, Average: 4.5

Exercise 9: Create Array and Change its Structure
python

import numpy as np

arr = np.arange(1, 21).reshape(4, 5)
print(arr)
# Output:
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])

Exercise 10: Conditional Selection of Values
python

import numpy as np

arr = np.arange(10)
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)
# Output: array([1, 3, 5, 7, 9])