🌟 Exercise 1 : Array Creation and Manipulation
Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:


array([3, 2, 0, 1, 2])


In [3]:
a = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print(a)


[3 2 0 1 2]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [7]:
a= np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Array(",a)

Array( [[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:

In [8]:
arr = np.random.rand(4, 5)
print(arr)

[[0.11352859 0.3691828  0.40790896 0.73686684 0.46564086]
 [0.2026866  0.34385919 0.85066152 0.85741784 0.10986979]
 [0.84881206 0.24373367 0.80988433 0.66177045 0.01595379]
 [0.75030192 0.89550013 0.98221879 0.3060347  0.69605525]]


🌟 Exercise 5 : Indexing Arrays
Instructions

Select the second row from a given 2D NumPy array.

Expected Output:


array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


In [9]:
arr = np.array([[21,22,23,22,22],
                [20, 21, 22, 23, 24],
                [21,22,23,22,22]])
second_row = arr[1]
print(second_row)

[20 21 22 23 24]


🌟 Exercise 6 : Reversing elements
Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [12]:
a= np.array([0,1,2,3,4,5,6,7,8,9])
reversed_a = a[::-1]
print(reversed_a)

[9 8 7 6 5 4 3 2 1 0]



🌟 Exercise 7 : Identity Matrix
Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


In [13]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions

Find the sum and average of a given 1D array.

Expected Output:


Sum: 45, Average: 4.5


In [14]:
arr = np.arange(10)
total = np.sum(arr)
average = np.mean(arr)
print(f"Sum: {total}, Average: {average}")

Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


In [15]:
array = np.arange(1, 21)  

reshaped_array = array.reshape(4, 5)
print("Reshaped to 4x5:\n", reshaped_array)


Reshaped to 4x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



🌟 Exercise 10 : Conditional Selection of Values
Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:

arr = np.arange(10)
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

In [16]:
arr = np.arange(10)
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
